config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
  	resources :videos
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
  	  namespace :storefront do
  	  	resources :videos, only: [:index, :show]
        resources :video_reviews, only: [:index, :create]
  	  end
  	end
  end						

  namespace :admin do
    resources :video_reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :video_feedback_reviews, only: [:index, :destroy]
    end
  end

  post '/video_reviews/:review_id/feedback(.:format)' => 'video_feedback_reviews#create', as: :video_feedback_reviews
end

app/controllers/spree/admin/video_reviews_controller.rb
module Spree
  module Admin
    class VideoReviewsController < ResourceController
      helper Spree::ReviewsHelper
     
      def index
        @s = if params[:ids].present?
                       scope.where(id: params[:ids].split(','))
                     else
                       scope.load.ransack(
                         params[:q]
                       ).result
                     end
      end

      def approve
        video_review = Spree::VideoReview.find(params[:id])
        if video_review.update_attribute(:approved, true)
          flash[:notice] = Spree.t(:info_approve_review)
        else
          flash[:error] = Spree.t(:error_approve_review)
        end

        redirect_to admin_video_reviews_path
      end

      def edit
        return if @video_review.video
        flash[:error] = "The reviewed video doesn't exist anymore"

        redirect_to admin_reviews_path
      end

      private

      def collection
          params[:q] = {} if params[:q].blank?
          @search = Spree::VideoReview.accessible_by(current_ability).ransack(params[:q])
          
          @collection = @search.result.
              includes([:video, :user, :video_feedback_reviews]).
              page(params[:page]).
              per(params[:per_page])
          @collection
      end

      def scope
          Spree::VideoReview.accessible_by(current_ability)
      end

    end
  end
end

app/controllers/spree/api/v2/storefront/video_reviews_controller.rb
module Spree
  module Api
  	module V2
      module Storefront
	    class VideoReviewsController < ::Spree::Api::V2::BaseController
   	      include Spree::Api::V2::CollectionOptionsHelpers
   	      include Spree::BaseHelper

	      before_action :require_spree_current_user, only:[:create]

	      def index
            video_reviews = collection.all.page(params[:page]).per(params[:per_page])
            render_serialized_payload { serialize_collection(video_reviews) }
          end

 	      def create
          video_review = Spree::VideoReview.new(review_params)
          video_review.video = Spree::Video.find_by(slug: params[:video_review][:video])
          if not video_review.video
            video_review.video = Spree::Video.find_by(id: params[:video_review][:video])
          end
		      video_review.user = spree_current_user 
		      video_review.ip_address = request.remote_ip
		      video_review.locale = I18n.locale.to_s if Spree::Reviews::Config[:track_locale]

		      video_review.save
		  
		    if video_review.persisted?
		      render_serialized_payload { serialize_resource(video_review) }
  		    else
		      render_error_payload(video_review.errors.full_messages.to_sentence)
     		end

	      end

	      private

	      def permitted_video_review_attributes
	        [:rating, :title, :review, :name, :show_identifier]
	      end

	      def review_params
	        params.require(:video_review).permit(permitted_video_review_attributes)
	      end

	      def model_class
            ::Spree::VideoReview
          end

          def scope
            ::Spree::VideoReview
          end

          def collection
            @collection ||= collection_finder.new(scope: scope, params: params).execute
          end

          def collection_finder
            Spree::VideoReviews::Find
          end

          def resource_serializer
            Spree::V2::Storefront::VideoReviewSerializer
          end

          def collection_serializer
            Spree::V2::Storefront::VideoReviewSerializer
          end
        
        end
      end
    end
  end
end

app/helpers/video_reviews_helper.rb
module VideoReviewsHelper
end

app/views/spree/admin/video_reviews/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals:  {target: @video_review } %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :review %>
  <%= f.text_area :review, wrap: 'virtual', rows: 10, cols: 60, class: 'form-control' %>
</div>

<% if Spree::Reviews::Config[:track_locale] %>
  <div class="form-group">
    <%= f.label :locale %>
    <%= f.select :locale, I18n.available_locales.map { |lc| [t(lc, default: lc.to_s), lc.to_s] }, {}, class: 'select2' %>
  </div>
<% end %>

app/views/spree/admin/video_reviews/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_review_for_html, link: @video_review.video.name) %>
<% end %>
<%= form_for [:admin, @video_review] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= render 'form', f: f %>
    </div>
    <div class="col-md-6">
      <% unless @video_review.title.blank? %>
        <h2><%= @video_review.title %></h2>
      <% end %>
      <blockquote>
        <%= simple_format(@video_review.review) %>
      </blockquote>
    </div>
  </div>
  <%= render 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/video_reviews/index.html.erb
<% content_for :page_title do %>
  <%= "Video Review" %>
<% end %>
<% if Spree.version.to_f < 4.2 %>
  <% svg_icon = '' %>
<% else %>
  <% svg_icon = '.svg' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_video_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree::VideoReview.human_attribute_name(:user) %>
            <%= f.text_field :name_cont, size: 25, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_title_cont, Spree::VideoReview.human_attribute_name(:title) %>
            <%= f.text_field :title_cont, size: 25, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_review_cont, Spree::VideoReview.human_attribute_name(:review) %>
            <%= f.text_field :review_cont, size: 25, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_approved_eq, Spree.t(:approval_status) %>
            <%= f.select :approved_eq, [[Spree.t(:all), nil], [Spree.t(:approved_reviews), true], [Spree.t(:unapproved_reviews), false]], {}, class: 'select2' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_video_name_cont, Spree::VideoReview.human_attribute_name(:video) %>
            <%= f.text_field :video_name_cont, size: 25, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
      </div>

      <div class="form-actions" data-hook="admin_video_reviews_index_search_buttons">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>

    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @collection  %>
<% if @collection.any? %>
  <table class="table" id="listing_video_reviews">
    <thead>
      <tr>
        <th><%= sort_link @search, :video, "Video" %></th>
        <th><%= sort_link @search, :rating, Spree::VideoReview.human_attribute_name(:rating) %></th>
        <th><%= sort_link @search, :user, Spree::VideoReview.human_attribute_name(:user) %></th>
        <th><%= sort_link @search, :ip_address, Spree::VideoReview.human_attribute_name(:ip_address) %></th>
        <th><%= sort_link @search, :created_at, Spree::VideoReview.human_attribute_name(:created_at) %></th>
        <th data-hook="admin_video_reviews_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |review| %>
        <tr data-hook="admin_video_reviews_index_rows" id="<%= dom_id review %>" class="<%= cycle('odd', 'even') %>">
          <td><%= link_to_if review.video, review.video.name, edit_admin_video_path(review.video) %></td>
          <td><%= txt_stars(review.rating) %></td>         
          <td><%= review.user_id ? link_to(review.user.try(:email), admin_user_path(review.user)) : Spree.t(:anonymous) %></td>
          <td><%= link_to_if review.ip_address, review.ip_address, "http://whois.domaintools.com/#{review.ip_address}", target: :blank %></td>
          <td><%= l review.created_at, format: :short %></td>
          <td data-hook="admin_video_reviews_index_row_actions" class="actions">
            <span class="d-flex justify-content-end">
              <%= link_to_with_icon "save#{svg_icon}", Spree.t(:approve), approve_admin_video_review_url(review), no_text: true, class: 'approve btn btn-sm btn-outline-secondary' unless review.approved %>
              <%= link_to_edit review, no_text: true, class: 'edit' %>
              <%= link_to_delete review, no_text: true %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource:plural_resource_name(Spree::VideoReview)) %>
  </div>
<% end %>
<%= render 'spree/admin/shared/index_table_options', collection: @collection  %>