config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
  	resources :videos
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
  	  namespace :storefront do
  	  	resources :videos, only: [:index, :show]
        resources :video_reviews, only: [:index, :create]
  	  end
  	end
  end						

  namespace :admin do
    resources :video_reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :video_feedback_reviews, only: [:index, :destroy]
    end
  end

  post '/video_reviews/:review_id/feedback(.:format)' => 'video_feedback_reviews#create', as: :video_feedback_reviews
end

app/models/spree/video.rb
class Spree::Video < ActiveRecord::Base
	validates :name,
              presence: true,
              uniqueness: { case_sensitive: false }

    validates :slug, uniqueness: true
    validates_associated :upload_video 

    has_one :vendor, class_name: 'Spree::Vendor',primary_key: 'vendor_id',  foreign_key: 'id'

    has_one :primary_product, class_name: 'Spree::Product', primary_key: 'primary_product_id',  foreign_key: 'id'
    has_one :upload_video, as: :viewable, dependent: :destroy, class_name: 'Spree::VideoUploadVideo'
    has_one :thumbnail, as: :viewable, dependent: :destroy, class_name: 'Spree::VideoThumbnail'
    
    has_many :video_secondary_products, class_name: 'Spree::VideoSecondaryProduct'
    has_many :products, through: :video_secondary_products, class_name: 'Spree::Product'

    has_many :video_taxons, class_name: 'Spree::VideoTaxon'
    has_many :taxons, through: :video_taxons, class_name: 'Spree::Taxon'

    has_many :video_reviews,class_name: 'Spree::VideoReview'

    def stars
      avg_rating.try(:round) || 0
    end

    def recalculate_rating
      self[:reviews_count] = video_reviews.reload.approved.count
      self[:avg_rating] = if reviews_count > 0
                            video_reviews.approved.sum(:rating).to_f / reviews_count
                          else
                            0
                          end
      save
    end
end

app/controllers/spree/admin/videos_controller.rb
module Spree
  module Admin
    class VideosController < ResourceController
      before_action :set_video, only: [:edit, :update, :destroy]
      before_action :load_data

      before_action only: [:create, :update] do
        set_vendor_id()
      end

      # GET /videos
      def index
        @videos = if params[:ids].present?
                       scope.where(id: params[:ids].split(','))
                     else
                       scope.load.ransack(
                         params[:q]
                       ).result
                     end
      end

      # GET /videos/1
      def show
      end

      # GET /videos/new
      def new
        @video = Video.new
      end

      # GET /videos/1/edit
      def edit
      end

      # POST /videos
      def create
        @video = Video.new(video_params.except(:upload_video))
        if @video.save
          if permitted_resource_params[:upload_video]
            @video.create_upload_video(attachment: permitted_resource_params[:upload_video])
            IO.copy_stream(permitted_resource_params[:upload_video].path, 'tmp/' + permitted_resource_params[:upload_video].original_filename.to_s)              
            Spree::Videos::GenerateVideoThumbnail.call(video_id:@video.id, screenshot_time:@video.thumbnail_screen_shot_time.to_f, video_name:permitted_resource_params[:upload_video].original_filename.to_s)
            Spree::Videos::QueueRequests.call(video_id:@video.id, 
              video_name:permitted_resource_params[:upload_video].original_filename.to_s,content_type: permitted_resource_params[:upload_video].content_type.to_s)
            # VideoWorker.perform_async(@video.id, permitted_resource_params[:upload_video].original_filename.to_s, permitted_resource_params[:upload_video].content_type.to_s)
          end
          redirect_to spree.admin_videos_url, notice: 'Video was successfully created.'
        else
          render :new
        end
      end

      # PATCH/PUT /videos/1
      def update

        old_seo_title = @video.thumbnail_screen_shot_time
        if permitted_resource_params[:upload_video]
          @video.create_upload_video(attachment: permitted_resource_params[:upload_video])
          IO.copy_stream(permitted_resource_params[:upload_video].path, 'tmp/' + permitted_resource_params[:upload_video].original_filename.to_s)
          Spree::Videos::GenerateVideoThumbnail.call(video_id:@video.id, screenshot_time:@video.thumbnail_screen_shot_time.to_f, video_name:permitted_resource_params[:upload_video].original_filename.to_s)
          Spree::Videos::QueueRequests.call(video_id:@video.id, 
              video_name:permitted_resource_params[:upload_video].original_filename.to_s,content_type: permitted_resource_params[:upload_video].content_type.to_s)
          # VideoWorker.perform_async(@video.id, permitted_resource_params[:upload_video].original_filename.to_s, permitted_resource_params[:upload_video].content_type.to_s)
        end

        if @video.update(video_params.except(:upload_video))
            if old_seo_title != @video.thumbnail_screen_shot_time
              Spree::Videos::GenerateVideoThumbnail.call(video_id:@video.id, video_url:main_app.url_for(@video.upload_video.try(:attachment)), screenshot_time:@video.thumbnail_screen_shot_time.to_f)
            end

          redirect_to spree.admin_videos_url, notice: 'Video was successfully updated.'
        else
          render :edit
        end
      end

      # DELETE /videos/1
      def destroy
        @video.destroy
        if @video.destroy
          flash[:success] = Spree.t('notice_messages.video_deleted')

          # flash[:success] = 'Video was successfully destroyed.'
        else
          flash[:error] = 'Video was not successfully destroyed.'
        end
        respond_with(@video) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      private

        # Use callbacks to share common setup or constraints between actions.
        def collection
          params[:q] = {} if params[:q].blank?
          @search = Spree::Video.accessible_by(current_ability).ransack(params[:q])

          @collection = @search.result.
              includes(video_includes).
              page(params[:page]).
              per(params[:per_page])
        end


        def video_includes
        {
          products: [],
          taxons: [],
          upload_video: [],
          vendor: [],
          primary_product: []
        }

      end

        def set_video
          @video = Video.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def video_params
          params.require(:video).permit(:vendor_id, :name,:slug,:description,:thumbnail_screen_shot_time,:seo_title,:seo_description,:available_on,:discontinue_on,:primary_product_id,:upload_video, product_ids: [], taxon_ids:[] )
        end

        def scope
          Spree::Video.accessible_by(current_ability)
        end

        def load_data
          if current_spree_user.has_spree_role?("admin")
            @products = Product.order(:name)          
          else
            @products = Product.order(:name).where(vendor_id: current_spree_user.vendors.active.ids) 
          end

          @taxons = Taxon.order(:name)
          @vendors = Vendor.order(Arel.sql('LOWER(name)')).where(state: "active")
        end

    end
  end
end

app/controllers/spree/api/v2/storefront/videos_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        class VideosController < ::Spree::Api::V2::BaseController
          include Spree::Api::V2::CollectionOptionsHelpers

          def index
            videos = collection.all.page(params[:page]).per(params[:per_page])
            render_serialized_payload { serialize_collection(videos) }
          end

          def show
            render_serialized_payload { serialize_resource(resource) }
          end
          
          private

          def model_class
            ::Spree::Video
          end

          def scope
            ::Spree::Video
          end

          def resource
            scope.find_by(slug: params[:id]) || scope.find(params[:id])
          end

          def collection
            @collection ||= collection_finder.new(scope: scope, params: params).execute
          end

          def collection_finder
            Spree::Videos::Find
          end

          def resource_serializer
            Spree::V2::Storefront::VideoSerializer
          end

          def collection_serializer
            Spree::V2::Storefront::VideoSerializer
          end

          def collection_meta(collection)
            super(collection).merge(filters: filters_meta)
          end

          def resource_meta(resource)
            {
            product_filters: resource_filters_meta
            }
          end

          def resource_options(resource)
            {
              meta: resource_meta(resource),
              include: resource_includes,
              fields: sparse_fields
            }
          end

          def filters_meta
            Spree::Api::Videos::FiltersPresenter.new().to_h
          end

          def resource_filters_meta
            Spree::Api::Products::FiltersPresenter.new(current_store, current_currency, params).to_h
          end

          def serialize_resource(resource)
            resource_serializer.new(
              resource,
              resource_options(resource).merge(params: serializer_params)
              # params: serializer_params,
              # include: resource_includes,
              # fields: sparse_fields
            ).serializable_hash
          end

    		end
      end
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/spree/admin/videos/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @video } %>

<div class="form-group">

    <% if current_spree_user.respond_to?(:has_spree_role?) && current_spree_user.has_spree_role?(:admin) %>
        <%= f.field_container :vendor do %>
          <%= f.label :vendor_id, Spree.t(:vendor) %>
          <%= f.collection_select(:vendor_id, @vendors, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
          <%= f.error_message_on :vendor %>
        <% end %>
    <% end %>



   <%= f.field_container :taxons do %>
    <%= f.label :taxon_ids, "Taxons" %>
    <% if can? :modify, Spree::VideoTaxon %>
      <%= f.select :taxon_ids, options_from_collection_for_select(@taxons, :id, :pretty_name, @video.taxon_ids),
                                { include_hidden: true },
                                  multiple: true,
                                  data: { autocomplete_url_value: 'taxons_api_v2',
                                          autocomplete_return_attr_value: 'pretty_name',
                                          autocomplete_multiple_value: true }, class: 'select2'%>
    <% elsif @video.taxons.any? %>
      <ul class="text_list">
        <% @video.taxons.each do |taxon| %>
          <li><%= taxon.pretty_name %></li>
        <% end %>
      </ul>
    <% else %>
      <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
    <% end %>
  <% end %>

  <%= f.field_container :primary_product_id do %>
    <%= f.label :primary_product_id %>
    <%= f.collection_select(:primary_product_id,@products, :id, :name,{ include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
    <%= f.error_message_on :primary_product_id %>
  <% end %>


  <%= f.field_container :products do %>
    <%= f.label :product_ids, "Secondary products" %>
    <% if can? :modify, Spree::VideoSecondaryProduct %>
      <%= f.select :product_ids, options_from_collection_for_select(@products, :id, :name, @video.product_ids),
                                { include_hidden: true },
                                  multiple: true,
                                  data: { autocomplete_url_value: 'videos_api_v2',
                                          autocomplete_return_attr_value: 'name',
                                          autocomplete_multiple_value: true }, class: 'select2'%>
    <% elsif @video.products.any? %>
      <ul class="text_list">
        <% @video.products.each do |product| %>
          <li><%= product.name %></li>
        <% end %>
      </ul>
    <% else %>
      <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :products) %></div>
    <% end %>
  <% end %>

  <%= f.field_container :name do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.error_message_on :name %>
  <% end %>

  <%= f.field_container :slug do %>
    <%= f.label :slug %>
    <%= f.text_field :slug, class: 'form-control' %>
    <%= f.error_message_on :slug %>
  <% end %><br>


  <%= f.field_container :upload_video do %>
    <%= f.label :upload_video %>
    <%= f.file_field :upload_video, accept: "video/*" %> <br><br>
    <%= video_tag(main_app.url_for(@video.upload_video.try(:attachment)), controls: true )if @video.upload_video %>
    <%= f.error_message_on :upload_video %>
  <% end %>

  <%= f.field_container :thumbnail do %>
    <%= f.label :thumbnail if @video.thumbnail %><br>
    <%= image_tag main_app.url_for(@video.thumbnail.url(:large)) if @video.thumbnail %>
  <% end %>

  <%= f.field_container :thumbnail_screen_shot_time do %>
    <%= f.label :video_thumbnail_screen_shot_time %>
    <%= f.text_field :thumbnail_screen_shot_time, class: 'form-control' %>
    <p><b><small>(Note: in seconds)</small></b></p>
    <%= f.error_message_on :thumbnail_screen_shot_time %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description %>
    <%= f.text_area :description, { rows: "10", class: "form-control spree-rte" } %>
    <%= f.error_message_on :description %>
  <% end %>

  <%= f.field_container :seo_title do %>
    <%= f.label :seo_title %>
    <%= f.text_field :seo_title, class: 'form-control' %>
    <%= f.error_message_on :seo_title %>
  <% end %>

  <%= f.field_container :seo_description do %>
    <%= f.label :seo_description %>
    <%= f.text_area :seo_description, class: 'form-control' %>
    <%= f.error_message_on :seo_description %>
  <% end %>

  <%= f.field_container :available_on do %>
    <%= f.label :available_on %>
    <%= f.date_field :available_on, class: 'form-control' %>
    <%= f.error_message_on :available_on %>
  <% end %>

  <%= f.field_container :discontinue_on do %>
    <%= f.label :discontinue_on %>
    <%= f.date_field :discontinue_on, class: 'form-control' %>
    <%= f.error_message_on :discontinue_on %>
  <% end %>
  
</div>

app/views/spree/admin/videos/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "Videos", spree.admin_videos_url %> /
  <%= @video.name %>
<% end %>

<% content_for :page_actions do %>
  <h5 style="padding-top:10px;">Avg Rating: <%=@video.avg_rating %></h5>&nbsp;
  <%= video_preview_link(@video.slug) %>
<% end %>

<%= form_for [:admin, @video] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/videos/index.html.erb
<% content_for :page_title do %>
  <%= "Videos" %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to "New Video", new_admin_video_url, { class: "btn-success", icon: 'add', id: 'new_admin_video_url' } %>
<% end%>

<% content_for :table_filter do %>
  <div data-hook="admin_videos_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_slug_cont, Spree.t(:slug) %>
            <%= f.text_field :slug_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>
        </div>
      </div>

      <div class="row">
        <% if current_spree_user.has_spree_role?("admin") %>
          <div class="col-md-6">
            <div class="form-group">
              <%= label_tag :q_vendor_name_cont, "Vendor"%>
              <%= f.text_field :vendor_name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
            </div>
          </div>
        <% end %>
      </div>

      <div data-hook="admin_vendors_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @collection  %>

<% if @collection.any? %>
<div class="table-responsive">
  <table class="table" id='listing_videos' data-hook>
    <thead>
      <tr data-hook="video_header">
        <th><%= "Name" %></th>
        <th><%= "Slug" %></th>
        <th><%= "Available On" %></th>
        <th><%= "Discontinue On" %></th>
        <th class="text-center"><%= "Avg Rating" %></th>
        <th ></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |video|
           @edit_url = edit_admin_video_url(video)
           @delete_url = spree.admin_video_url(video) %>
        <tr id="<%= spree_dom_id video %>" data-hook="tax_row">
          <td><%= video.name %></td>
          <td><%= video.slug %></td>
          <td><%= video.available_on %></td>
          <td><%= video.discontinue_on %></td>
          <td class="text-center"><%= video.avg_rating %></td>
          <td class="actions">
            <span class="d-flex justify-content-end">
              <%= link_to_edit(video, no_text: true) if can? :edit, video %>
              <%= link_to_delete(video, no_text: true)if can? :delete, video , method: :delete%>
            </span>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Video)) %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @collection  %>

app/views/spree/admin/videos/new.html.erb
<% content_for :page_title do %>
  <%= link_to "Videos", spree.admin_videos_url %> /
  <%= "New Video" %>
<% end %>

<%= form_for [:admin, @video] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>