config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
  	resources :videos
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v2 do
  	  namespace :storefront do
  	  	resources :videos, only: [:index, :show]
        resources :video_reviews, only: [:index, :create]
  	  end
  	end
  end						

  namespace :admin do
    resources :video_reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :video_feedback_reviews, only: [:index, :destroy]
    end
  end

  post '/video_reviews/:review_id/feedback(.:format)' => 'video_feedback_reviews#create', as: :video_feedback_reviews
end

app/controllers/spree/admin/video_feedback_reviews_controller.rb
module Spree
  module Admin
    class VideoFeedbackReviewsController < ResourceController
      belongs_to 'spree/video_review'

      def index
        @collection = parent.video_feedback_reviews
      end
    end
  end
end

app/helpers/video_feedback_reviews_helper.rb
module VideoFeedbackReviewsHelper
end

app/views/spree/admin/video_feedback_reviews/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:feedback_review_for, review: @video_review.title) %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_reviews), admin_video_reviews_path, icon: 'back' %>
<% end %>
<% if @collection.any? %>
  <table class="table" id="listing_video_feedback">
    <thead>
      <tr>
        <th><%= Spree.t(:user) %></th>
        <th><%= Spree.t(:stars) %></th>
        <th><%= Spree.t(:date) %></th>
        <th data-hook="admin_video_feedback_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |feedback| %>
        <tr id="<%= dom_id(feedback) %>" class="<%= cycle('odd', 'even') %>">
          <td><%= feedback.user.try(:login) || Spree.t(:anonymous) %></td>
          <td><%= feedback.rating %></td>
          <td><%= l(feedback.created_at, format: :short) %></td>
          <td data-hook="admin_video_feedback_row_header_actions" class="actions">
            <span class="d-flex justify-content-end">
            <%= link_to_delete feedback, no_text: true %>
          </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_results) %>
  </div>
<% end %>